global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi_service"
    static_configs:
      - targets: ["localhost:8000"]

  - job_name: "custom_exporter"
    static_configs:
      - targets: ["localhost:8001"]
